defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1
  port: 3306
  pool: 5

development:
  <<: *defaults
  database: zombies_development

test:
  <<: *defaults
  database: zombies_test

production:
  <<: *defaults
  database: zombies_production
